const Constants = {
	SIGN_IN:"SIGN_IN",
	SIGN_OUT:"SIGN_OUT",
	UPDATE_USER:"UPDATE_SIGNED_IN_USER",
	SAVE_OTHER_USER:"SAVE_OTHER_USER",
	SAVE_OTHER_USERS:"SAVE_OTHER_USERS",
	SAVE_OTHER_GROUP:"SAVE_GROUP",
	SAVE_OTHER_GROUPS:"SAVE_OTHER_GROUPS",
	DELETE_USER:"DELETE_USER",
	DELETE_GROUP:"DELETE_GROUP",

	/*
	UPDATE_GROUP:"UPDATE_GROUP",
	SAVE_ELIGIBLE_PLAYERS:"SAVE_ELIGIBLE_PLAYERS",
	ADD_PLAYER:"ADD_PLAYER",
	REMOVE_PLAYER:"REMOVE_PLAYER",
	SET_DASHBOARD_FILTER:"SET_DASHBOARD_FILTER",
	ADD_DATASET:"ADD_DATASET",
	ADD_DATAPOINT:"ADD_DATAPOINT",
	SAVE_SELECTIONS:"SAVE_SELECTIONS",
	START_CHANGING_SELECTIONS:"START_CHANGING_SELECTIONS",
	*/
	START: "START",
	END: "END",
	OPEN_DIALOG:"OPEN_DIALOG",
	CLOSE_DIALOG:"CLOSE_DIALOG",
	RESET_STATUS:"RESET_STATUS",
	NO_ACTION:"NO_ACTION",
	ERROR:"ERROR"
}

export default Constants